package com.ucjc;

import java.io.FileReader;
import java.util.logging.Logger;

import com.ucjc.compiled.generated.Lexer;
import com.ucjc.compiled.generated.Parser;
import com.ucjc.compiled.generated.Sym;

import java_cup.runtime.Symbol;

public class App {
    private static final Logger logger = Logger.getLogger(App.class.getName());

    public static void main(String[] args) throws Exception {
        // Obtener la ruta relativa de la carpeta "database"
        String inputFilePath = "C:\\Users\\franc\\Desktop\\Programacion\\Proyecto Logica\\spotify-song-searcher\\src\\main\\resources\\input.txt";

        // Construir la ruta completa al archivo "input.txt"
        Lexer lexer = new Lexer(new FileReader(inputFilePath));

        // Debugging: Print tokens generated by the lexer
        try {
            while (true) {
                Symbol token = lexer.next_token();

                if (token.value != null) {
                    if (!token.value.equals(0)) {
                        String tokenText = token.value.toString();
                        System.out.println("Token: " + token.sym + ", Text: " + tokenText);
                    }
                } else {
                    System.out.println("Token: " + token.sym + ", Text: null");
                }

                if (token.sym == Sym.EOF) {
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        // Continue with parser
        Parser parser = new Parser(lexer);

        Symbol result = parser.parse();

        System.out.println(result);

        // try {
        //     parser.parse();
        //     System.out.println("Consulta analizada correctamente.");
        // } catch (Exception e) {
        //     System.err.println("Error al analizar la consulta: " + e.getMessage());
        // }


    }
}
